import type { Metadata } from "next";
import "./globals.css";
import { raleway } from "@/components/font";
import NavBar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "MyPortofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gradient-to-r from-gray-700 to-black text-white font-bold ${raleway.className}`}
      >
        <div>
          <NavBar />
        </div>

        <div className="">
          {children}
        </div>
      </body>
    </html>
  );
}
